/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank.ocr.kata.testdouble;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Stream;

public class AccountNumberProcessor {
    public String getGreeting() {
        return "Application WIP!";
    }

    public static void main(String[] args) {
        System.out.println(new AccountNumberProcessor().getGreeting());
    }

    public Integer convertCharsToInteger(List<List<String>> inputNumberStrings) {
        String col0Row0 = inputNumberStrings.get(0).get(0);
        String col0Row1 = inputNumberStrings.get(1).get(0);
        String col0Row2 = inputNumberStrings.get(2).get(0);
        String firstVerticalMatch = col0Row0 + col0Row1 + col0Row2;
        if(firstVerticalMatch.equals(Key.matchTwo)){
            return 2;
        }

        String col1Row0 = inputNumberStrings.get(0).get(1);
        String col1Row1 = inputNumberStrings.get(1).get(1);
        String col1Row2 = inputNumberStrings.get(2).get(1);
        String secondVerticalMatch = col1Row0 + col1Row1 + col1Row2;
        HashMap<String, Integer> secondVerticalMatchKey = Key.generateSecondMatchKey(firstVerticalMatch);
        if(secondVerticalMatchKey.containsKey(secondVerticalMatch)){
            return secondVerticalMatchKey.get(secondVerticalMatch);
        }

        return null;
    }

    public List<List<String>> convertToList(Path filePath) throws IOException {
        try (Stream<String> lines = Files.lines(filePath)) {
            Stream<List<String>> splitLinesStream =
                    lines.map(line -> Arrays.stream(line.split("")).toList());
            return splitLinesStream.toList();
        }
    }
}
