/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank.ocr.kata.testdouble;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Stream;

public class AccountNumberProcessor {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new AccountNumberProcessor().getGreeting());
    }

    public Integer convertCharsToInteger(List<List<String>> inputNumberStrings) {
        String col0Row0 = inputNumberStrings.get(0).get(0);
        String col0Row1 = inputNumberStrings.get(1).get(0);
        String col0Row2 = inputNumberStrings.get(2).get(0);
        String firstVerticalMatch = col0Row0 + col0Row1 + col0Row2;
        HashMap<String, Integer> firstVerticalMatchKey = Key.generateFirstMatchKey();
        if(firstVerticalMatchKey.containsKey(firstVerticalMatch)){
            return firstVerticalMatchKey.get(firstVerticalMatch);
        }



        return null;
    }

    public List<List<String>> convertToList(Path filePath) throws IOException {
        try (Stream<String> lines = Files.lines(filePath)) {
            Stream<List<String>> splitLinesStream =
                    lines.map(line -> Arrays.stream(line.split("")).toList());
            return splitLinesStream.toList();
        }
    }
}
